import type { Metadata } from "next"
import ThemeProvider from "@/src/theme/ThemeProvider"
import clsx from "clsx"
import { Inter } from "next/font/google"
import Header from "@/src/features/layout/Header"
import "./globals.css"
import { Footer } from "@/src/features/layout/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "bg-background h-full w-full")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col items-center h-full w-full">
            <Header />
            <div className="flex max-w-lg m-auto py-12 w-full">{children}</div>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
